name: Algorithm Problem Tracker

on:
  schedule:
    - cron: '16 20 * * 1,2,3,4,5'  # UTC 20:16 = 한국 05:16
    # - cron: '22 22 * * 1,2,3,4,5'  # UTC 월~금 22:22 = 한국 화~토 7:22
    # - cron: '*/5 * * * *'  # 5분마다 실행 (테스트용)
  workflow_dispatch:

jobs:
  send-commit-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm install discord.js axios
      
    - name: Send algorithm problem report
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        REPOS: ${{ secrets.REPOS }}
      run: node serverless-bot.js